version: '3.8'
services:

  bot-private-db:
    image: postgres:14-alpine
    container_name: db_bot_private
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  main-service:
    image: main-service
    build: ./main-service
    container_name: ms_bot_private
    restart: on-failure
    depends_on:
      - bot-private-db
    environment:
      - TG_NAME=${TG_NAME}
      - TG_TOKEN=${TG_TOKEN}
      - DB_NAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_HOST=bot-private-db
      - DB_PORT=5432