server:
  port: ${SERVER_EXTERNAL_PORT_DISPATCHER}

localeTag: ${LOCALE_TAG}

logging:
  level:
    com:
      github:
        jon7even: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: DEBUG
        transaction: INFO
      hibernate:
        SQL: DEBUG
        type.descriptor:
          sql:
            BasicBinder: TRACE

# Configuration for the 'ci' profile
bot:
  token:
    name: ${TELEGRAM_BOT_NAME_PROD}
    token: ${TELEGRAM_BOT_PASS_PROD}
  security:
    keyPass: ${SECURITY_KEY_PASS_BOT_PROD}
    attemptsAuth: ${SECURITY_ATTEMPTS_AUTH_PROD}

spring:
  config:
    activate:
      on-profile: ci

  liquibase:
    enabled: true
    default-schema: ${SCHEMA_APP}
    change-log: classpath:db/changelog/db.changelog-master.xml

  main:
    banner-mode: off

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default-schema: ${SCHEMA_APP}
    open-in-view: false

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_AMQP_PORT_LOCAL}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT_LOCAL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      connection-timeout: 270
---
# Configuration for the 'test' profile
server:
  port: ${SERVER_TEST_PORT_DISPATCHER}

bot:
  token:
    name: ${TELEGRAM_BOT_NAME_TEST}
    token: ${TELEGRAM_BOT_PASS_TEST}
  security:
    keyPass: ${SECURITY_KEY_PASS_BOT_TEST}
    attemptsAuth: ${SECURITY_ATTEMPTS_AUTH_TEST}

logging:
  level:
    com:
      github:
        jon7even: DEBUG
    org:
      springframework:
        orm:
          jpa: DEBUG
          JpaTransactionManager: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor:
          sql:
            BasicBinder: DEBUG

spring:
  config:
    activate:
      on-profile: test

  liquibase:
    enabled: true
    default-schema: ${SCHEMA_APP}
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        default-schema: ${SCHEMA_APP}
    open-in-view: false

  rabbitmq:
    host: ${RABBIT_HOST_TEST}
    port: ${RABBIT_AMQP_PORT_LOCAL_TEST}
    username: ${RABBIT_USER_TEST}
    password: ${RABBIT_PASS_TEST}